Update tutorial_i.ipynb (#383)
causal programming without tears tutorial 

```python
smokes = pyro.sample("smokes", Bernoulli(smokes_cpt[stress.int()]))
    cancer = pyro.sample("cancer", Bernoulli(cancer_cpt[stress.int(), smokes.int()]))
```

to:

```python
smokes = pyro.sample("smokes", Bernoulli(smokes_cpt[stress.long()]))
    cancer = pyro.sample("cancer", Bernoulli(cancer_cpt[stress.long(), smokes.long()]))
```

This fixes the following error message.

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[11], line 8
      4 smokes_cpt  = torch.tensor([0.2, 0.8])
      5 cancer_cpt  = torch.tensor([[0.1, 0.15], 
      6                             [0.8, 0.85]])
----> 8 pyro.render_model(causal_model, (stress_pt, smokes_cpt, cancer_cpt))

File ~/.pyenv/versions/pyciemss-main/lib/python3.10/site-packages/pyro/infer/inspect.py:585, in render_model(model, model_args, model_kwargs, filename, render_distributions, render_params)
    583 # Get model relations.
    584 if not isinstance(model_args, list) and not isinstance(model_kwargs, list):
--> 585     relations = [get_model_relations(model, model_args, model_kwargs)]
    586 else:  # semisupervised
    587     if isinstance(model_args, list):

File ~/.pyenv/versions/pyciemss-main/lib/python3.10/site-packages/pyro/infer/inspect.py:285, in get_model_relations(model, model_args, model_kwargs)
    283 with torch.random.fork_rng(), torch.no_grad(), pyro.validation_enabled(False):
    284     with TrackProvenance():
--> 285         trace = poutine.trace(model).get_trace(*model_args, **model_kwargs)
    287 sample_sample = {}
    288 sample_param = {}

File ~/.pyenv/versions/pyciemss-main/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py:198, in TraceHandler.get_trace(self, *args, **kwargs)
    190 def get_trace(self, *args, **kwargs):
    191     """
    192     :returns: data structure
    193     :rtype: pyro.poutine.Trace
   (...)
    196     Calls this poutine and returns its trace instead of the function's return value.
    197     """
--> 198     self(*args, **kwargs)
    199     return self.msngr.get_trace()

File ~/.pyenv/versions/pyciemss-main/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py:174, in TraceHandler.__call__(self, *args, **kwargs)
    170 self.msngr.trace.add_node(
    171     "_INPUT", name="_INPUT", type="args", args=args, kwargs=kwargs
    172 )
    173 try:
--> 174     ret = self.fn(*args, **kwargs)
    175 except (ValueError, RuntimeError) as e:
    176     exc_type, exc_value, traceback = sys.exc_info()

Cell In[10], line 6, in causal_model(stress_pt, smokes_cpt, cancer_cpt)
      4 def causal_model(stress_pt, smokes_cpt, cancer_cpt):
      5     stress = pyro.sample("stress", Bernoulli(stress_pt))
----> 6     smokes = pyro.sample("smokes", Bernoulli(smokes_cpt[stress.int()]))
      7     cancer = pyro.sample("cancer", Bernoulli(cancer_cpt[stress.int(), smokes.long()]))
      8     # For now we only return smokes because we need to return a single value for the predictive handler.
      9     # We need to return smokes because the trace address for `smokes` does not include the interventions.
     10     # TODO: address this in the future.

File ~/.pyenv/versions/pyciemss-main/lib/python3.10/site-packages/pyro/ops/provenance.py:67, in ProvenanceTensor.__torch_function__(cls, func, types, args, kwargs)
     64 @classmethod
     65 def __torch_function__(cls, func, types, args=(), kwargs=None):
     66     _args, _kwargs = detach_provenance([args, kwargs or {}])
---> 67     ret = func(*_args, **_kwargs)
     68     return track_provenance(ret, get_provenance([args, kwargs]))

IndexError: tensors used as indices must be long, byte or bool tensors
```